# Generated by Django 5.2.17 on 2026-10-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0016_fix_agency_questionnaire_template_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='source_language',
            field=models.CharField(default='en-us', max_length=35),
        ),
        migrations.CreateModel(
            name='QuestionnaireTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=35)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.questionnaire')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'language_code'), name='uniq_questionnaire_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=35)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.questionsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'language_code'), name='uniq_section_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=35)),
                ('question_text', models.TextField(blank=True)),
                ('translated_config', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='questionnaires.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'language_code'), name='uniq_question_translation_language')],
            },
        ),
    ]
